### ISSUE TITLE
Interactively set 'color_terminal'

### ISSUE THREAD

**Issue by kadrlica** [mgckind/easyaccess#104]
I haven't been able to find a good way to toggle `color_terminal` off when using the API. This is because of the way that we define the global function `colored` so that it doesn't respect the `color_terminal` setting in the config file.

**Comment by kadrlica** [comment]
I would add that I think the default should be for color to be off in the API, but that is a personal preference.

**Comment by kadrlica** [comment]
It appears that the toggle works for turning off the color, but not for turning it on again.
```
> easyaccess
~> ?
[color on]
~> config color_terminal set false
~> ?
[color off]
~> config color_terminal set true
~> ?
[color off]
```
However, if I exit the interactive session and login again the color will be on. It appears that any call to `config color_terminal set` turns off the color, regardless of set value.

```
[color on]
~> config color_terminal set true
[color off]
```

**Comment by mgckind** [comment]
it needs to be yes/no (any other string will be False). Still, I see a small bug there, hold on

**Comment by kadrlica** [comment]
Turns out that I need to re-read the instructions. The only value that enables color is "yes" or "y". I've added this as an improvement in #114.

**Comment by mgckind** [comment]
Yes, that might be better. I found the bug and fixed it. It was that if you set color_terminal to 'no' when you log in again you couldn't turn it back on again interactively. but other than that, yes/no should do the trick.
