### ISSUE TITLE
Left justify comment column in 'describe_table'

### ISSUE THREAD

**Issue by kadrlica** [mgckind/easyaccess#105]
The comment column printed by `describe_table` is currently right-justified (like all other columns. However, the comments column contains strings of very different lengths, so I think it makes more sense for this column to be left justified.

**Comment by kadrlica** [comment]
I haven't been able to find a `pandas` display option that allows this to be done, but the `DataFrame.to_string` options:

```
width = df['COMMENTS'].str.len().max()
format = lambda s: '{: <{width}}'.format(s,width=width)
print(df.to_string(formatters={'COMMENTS':format}))
```

Adding this to to `do_describe_table` will left-justify comments (making them much easier to read) but will keep the other columns right justified. Column headers can be left justified by with the `justify='left'` argument of `to_string`, but I'm not sure if this can be done for a single header.

**Comment by mgckind** [comment]
I think I got it, this is a good suggestion. We can justify header by renaming the column :). Need to test further before closing
