### ISSUE TITLE
error in creating DES_SERVICES file

### ISSUE THREAD

**Issue by chihway** [mgckind/easyaccess#108]
(easyaccess)[chihway@midway-login2 ~]$ easyaccess 

```
Error in DES_SERVICES config file, creating a new one...
File might not exists or is not configured


Adding section db-dessci to des_service file

Enter username : chihway
name 'chihway' is not defined
Traceback (most recent call last):
  File "/home/chihway/anaconda3/envs/easyaccess/bin/easyaccess", line 2754, in <module>
    desconf = config_mod.get_desconfig(desfile, db)
  File "/home/chihway/anaconda3/envs/easyaccess/lib/python2.7/site-packages/easyaccess/config_ea.py", line 166, in get_desconfig
    if value.message.code == 1017:
AttributeError: 'str' object has no attribute 'code' 
```

**Comment by mgckind** [comment]
Hi Chihway,

Are you using a dual keyboard? That problem usually happens for dual keyboards on linux machines.
I'd recommend to create that file manually (in the tutorial there is an example) if this is not the case send me an email.

Cheers

**Comment by chihway** [comment]
Hi Matias, 

Yeah Alex helped me fix this in the end (by copying my local config file over), so easy access is working for me now. But I guess he wanted to also flag it as a potential issue. 

(for reference, I have a mac and may have a usb keyboard plugged in when this happened… but hard to imagine how this is affecting… ) 

Thanks,
Chihway

**Comment by mgckind** [comment]
Thanks, yes those error are hard to track, I know dual keyboard also gives problems. I'll leave this open for now as a reminder.

**Comment by mgckind** [comment]
Found the error for this particular issue and a fix for py2 and py3. For context, it should have been `raw_input` for getting input from user (in some cases),  so the input is parsed as string instead of code. python3 doesn't have the problem but move raw_input to input.
