### ISSUE TITLE
easyaccess unresponsive after Oracle error

### ISSUE THREAD

**Issue by coljac** [mgckind/easyaccess#130]
I'm running easyaccess using the docker container on the docker hub.

If I make a syntax error in a query, and get an error message from Oracle (printed in red by easyaccess), it returns me to the prompt but the subsequent command will not run, and the tool becomes unresponsive. I have to kill the docker container and start again.

To reproduce:

```
DESDB ~> select count(blah from spod;

    |   ☆          |  Ctrl-C to abort; 
<class 'cx_Oracle.DatabaseError'>
ORA-00907: missing right parenthesis

DESDB ~> [Anything such as a query or 'exit' command - hangs]
```

**Comment by mgckind** [comment]
Thanks @coljac!. I haven't had much feedback from the Docker Image. You are right, after a error the image gets frozen. I think I know the reason and its related to running a subprocess from inside easyaccess. I'll try to debug it and get it fixed. Thanks again for reporting it

**Comment by MatSmithAstro** [comment]
I can report the same issue on a iMac running El Capitan (10.11.6). easyaccess hangs on any query after a cx_Oracle error in the previous query. Note that the error does not manifest itself if the error is not related to cx_Oracle: e.g. after trying to write out the results to a .txt file (which is not supported), I can re-run the query fine. 
I'm running easyaccess 1.4.3 using anaconda (4.3.1) python (3.6.0) with the latest cx_Oracle from pip.

**Comment by mgckind** [comment]
thanks @wycombe7, I need to make sure this get fixed, regarding .txt, is not supported as extension but if you use .tab extension and those columns will be space-separated

**Comment by MatSmithAstro** [comment]
Thanks @mgckind for looking into this. If it helps, this is a problem that's only appeared (for me) in the latest version of easyaccess: version 1.4.2 ran smoothly without complaint. 
Thus, the problem either lies there, in the recent database update or another recent system update (e.g. cx_Oracle 12?). I shall check my system to see if anything obvious pops out. (and thanks for the info on .tab: that's really useful!)

**Comment by coljac** [comment]
Hi @mgckind,
Any update on this issue? I notice the docker image is a minor release behind; could that contribute to this problem?

**Comment by chrisfrohmaier** [comment]
Hi @mgckind, Has a solution been found for this problem? 
I can report I am experiencing the same issues. My system: macOS High Sierra 10.13.3, python 3.6.1, conda 4.4.10, easyaccess 1.4.4-dev-3b3b729
Any advice would be much appreciated.
