### ISSUE TITLE
have easyaccess use its own logger, not the default, so it doesn't mess up other logging configuraitons

### ISSUE THREAD

**Issue by ehneilsen** [mgckind/easyaccess#132]
When I load easyaccess as a python module (to use non-interactively), it messes up my logging configuration, so that I get every logging message twice, once in the format I want, and once in the one preferred by easyaccess. The easy way around it is for easyacces to use its own instance of logging.Logger, not the default one.

Yes, I can "solve" this by having my script use its own instance of logging.Logger rather than the default one, but it shouldn't have to: distributed modules should leave the default logger alone, and define and use their own instances of logging.Logger.

**Comment by kadrlica** [comment]
I think this was an issue with the old `logging.basicConfig` call:
https://github.com/mgckind/easyaccess/blob/cb98a6f50b5c48a0c11d50dec1470ea20d62f0a2/bin/easyaccess#L71-L72

However, I don't think we were ever using `logging` (a la #21) and I think this has been removed in more recent versions (v1.4.2). @ehneilsen can you confirm whether or not this is an issue with new versions of easyaccess?

**Comment by ehneilsen** [comment]
I just tested with the newer version (1.4.2, by way of anaconda environment des17a on the DES cluster at Fermilab) and indeed it seems not to be a problem there.
