### ISSUE TITLE
There was an error when refreshing the metadata

### ISSUE THREAD

**Issue by richardgmcmahon** [mgckind/easyaccess#139]
I am running easyaccess 1.4.3. 

Connected as richardgmcmahon to dessci.

on OSX Yosemite 10.10.5 with conda and Python 2.7
Python 2.7.13 |Anaconda custom (x86_64)| (default, Dec 20 2016, 23:05:08)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin

When I start easyaccess I get:

Connecting to DB ** dessci ** ...
Loading metadata into cache...
There was an error when refreshing the metadata

I can reproduce the error:

DESDB ~> refresh_metadata_cache
Loading metadata into cache...
There was an error when refreshing the metadata
describe_table works as follows:

DESDB ~> describe_table Y3A1_COADD_OBJECT_SUMMARY

    |       ☆      |  Ctrl-C to abort;  Rows : 182, Rows/sec: 201
Description of Y3A1_COADD_OBJECT_SUMMARY commented as: 'None'
Estimated number of rows: 399578351

**Comment by coljac** [comment]
Using the docker image, this error appears every time I start the container.

**Comment by mgckind** [comment]
This is now fixed in 1.4.4
