### ISSUE TITLE
Saving Query to H5 breaks down for large numbers of rows

### ISSUE THREAD

**Issue by cpadavis** [mgckind/easyaccess#140]
If you perform a query and save to .h5, any query with more than one trip will keep overwriting the trips.

An easy check:

DESDB ~> select COADD_OBJECT_ID from Y3A2_COADD_OBJECT_SUMMARY where rownum < 100000 ; > test_100000.h5

then if you load test_100000.h5, you'll discover it only has (at least on my end) 9999 rows, which is the number of rows per trip.

In contrast, saving to a fits file is fine :)

**Comment by mgckind** [comment]
it definitely looks a bug, thanks @cpadavis, haven't had much feedback on hdf5 files.  I'll take a look, a workaround would be to increase the rows per trip inside easyaccess or from the configuration file $HOME/.easyaccess/config.ini
`DESDB ~> config prefetch set 50000`

I won't solve the problem though for very large files (but you can also adjust the GB per file and write multiple files as well)

**Comment by mgckind** [comment]
I found the error, it was actually a 'new' pandas feature
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_hdf.html
it was not appending data correctly, they changed the format for HDF5 files  and now by default it doesn't append to the file (there is a keyword format={'f','t') ).  I'll fix it for the next release. Thanks for reporting this.
