### ISSUE TITLE
Update documentation for .desservices.ini file for server

### ISSUE THREAD

**Issue by bechtol** [mgckind/easyaccess#144]
In .desservices.ini, the server should be desdb.ncsa.illinois.edu for for destest database

This is a documentation update. See for example:

http://matias-ck.com/easyaccess/#/Authentication

**Comment by kadrlica** [comment]
Maybe change needs to be made here:
https://github.com/mgckind/easyaccess/blob/b48863813bcb101b6a87c68002ce0504b0a9a253/easyaccess/config_ea.py#L195
