### ISSUE TITLE
Update DESDM dtypes

### ISSUE THREAD

**Issue by kadrlica** [mgckind/easyaccess#147]
It appears that the DESDM database type convention has changed for Y3. The `MAG` and `MAGERR` columns have changed from `NUMBER` to be `BINARY_FLOAT`. @mgckind @rgruendl can you confirm that this is the current (and future) convention?

**Comment by kadrlica** [comment]
Current DESDM convention can be found in [eautils/dtypes.py](https://github.com/mgckind/easyaccess/blob/b48863813bcb101b6a87c68002ce0504b0a9a253/easyaccess/eautils/dtypes.py#L169-L236)

**Comment by rgruendl** [comment]
Alex,

Originally (previous DB admin) these columns were set to a number type to allow for better indexing... however, this switched within the Y3 release as the more prevalent use cases showed that these columns were being used in arithmetic expressions where having the values cast as a binary floats would allow queries to execute faster.

Robert

________________________________

**Comment by kadrlica** [comment]
Thanks @rgruendl. Can I take the format of Y3 to be the new "standard"? If so, I will update all dtypes to match that.

**Comment by rgruendl** [comment]
yes, you can take it as the new standard

________________________________
