### ISSUE TITLE
describe_table does not work

### ISSUE THREAD

**Issue by stringkm** [mgckind/easyaccess#152]
My _describe_table_ command returns "Table not found." in des-sci on easyaccess 1.4.3.  _find_tables_ and SQL select statements work for a given table. I have also tried refreshing the metadata and putting in the table owner like this _describe_table owner.table_name_. Unfortunately, none of these seems to do the trick. Thank you in advance for checking into this!

**Comment by kadrlica** [comment]
Which table are you trying to describe?

**Comment by stringkm** [comment]
It hasn't been working for pretty much any table. But here's a few I've tried: 
![image](https://user-images.githubusercontent.com/15678547/43738469-5a60963c-998a-11e8-98c9-5c7b0aafee71.png)
It may be an issue related to my account. I'm not sure.

**Comment by kadrlica** [comment]
Hmmm, I just tried the first one `Y3A2_MOF` and got the full table information. What version of easyaccess are you using?

**Comment by stringkm** [comment]
I'm using version 1.4.3 on Ubuntu 14.04.

**Comment by kadrlica** [comment]
I just tried with 1.4.3 on SL6. Any ideas @mgckind?

**Comment by mgckind** [comment]
Is not the first time I've heard about this weird issue, but I haven't been able to reproduce it on any of my machines unfortunately.  My guess is that there is an error throwing which make it look like there is no description. is not on easyaccess side, not Oracle. I'll take a look

**Comment by mgckind** [comment]
@stringkm what version of cx_Oracle are you using?
`python -c "import cx_Oracle; print(cx_Oracle.__version__)"`

**Comment by stringkm** [comment]
Hi Matias! I have version 5.3.

**Comment by mgckind** [comment]
@stringkm  Can you try these commands please? (I'm trying to at least find the error)
```
import easyaccess as ea
con=ea.connect()
qcom = "select comments from all_tab_comments atc where atc.table_name = 'Y3_GOLD_2_2'"
comment_table = con.query_results(qcom)[0][0]
```

**Comment by stringkm** [comment]
Here's what I got. 

![image](https://user-images.githubusercontent.com/15678547/43787014-a02e5f32-9a2f-11e8-8e69-b4f806a73db4.png)

**Comment by mgckind** [comment]
Thanks, so that's the issue. Now, it's a weird error. I'll dig up  bit more.

**Comment by stringkm** [comment]
Thanks Matias!

**Comment by mgckind** [comment]
Maybe @madamow can help?

**Comment by madamow** [comment]
@stringkm could you check if this issue is gone after change in prefetch? Just to be sure.

**Comment by stringkm** [comment]
Describe_table runs without error. So glad it is working again! Thank you!

**Comment by mgckind** [comment]
are you kidding me? I completely ruled out that option since the describe table isn't returning large number of rows.... I usually recommend changing this parameter for getting a good number of rows in a normal query... still is a mistery the memory leak, but this is good for me
