### ISSUE TITLE
appears to hang after an invalid query

### ISSUE THREAD

**Issue by beckermr** [mgckind/easyaccess#157]
For me, v1.4.5 hangs after I try to execute a query after I tried to execute an invalid query.

**Comment by mgckind** [comment]
Thanks, yes this is an error I haven't been able to fully reproduce, unfortunately, see #130  
What system are you running?

**Comment by beckermr** [comment]
osx mojave

**Comment by beckermr** [comment]
OK closing this since it is a dupe.
