### ISSUE TITLE
More graceful failure when oracle client library is not installed

### ISSUE THREAD

**Issue by ngoldbaum** [mgckind/easyaccess#158]
Current if the oracle client library can't be located (for example, if someone installs `easyaccess` from pip but fails to install the oracle binaries), this happens:

```
$ easyaccess -s desdr

Error in DES_SERVICES config file, creating a new one...
File might not exists or is not configured correctly


Adding section db-desdr to des_service file

Enter username : ngoldbaum
Enter password :

DPI-1047: 64-bit Oracle Client library cannot be loaded: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help
```

While the error message does point to the installation instructions for the oracle client, this is such a common pitfall that the error message itself should try to explain what's going wrong in less technical language, something like "easyaccess was unable to load the oracle client library, please follow the installation instructions below:"

I would also encourage you to more prominently explain in the installation instructions in the readme that the oracle client library needs to be installed separately. I'm not sure offhand if that applies only to the pip installation (what I used) or to the conda installation as well.

See https://github.com/openjournals/joss-reviews/issues/1022

**Comment by mgckind** [comment]
Thanks, It's true. That error comes directly from Oracle and can't be modified, we can add a test to check whether the library was properly installed (given that cx_Oracle is a requirement, it checks for the installation of the Oracle client first, but not whether is properly installed)

**Comment by ngoldbaum** [comment]
Yeah, I'd suggest adding import guards around the `cx_Oracle` import, capture the exception, and then reraise with a better error message.

**Comment by mgckind** [comment]
The problem with that is that every Oracle Error is different, from syntax errors to connection errors, locks, etc. I have those guards and actually print the errors instead of raising an Exception. I can definitely add something regarding the first time running to make sure everything is ok.

**Comment by ngoldbaum** [comment]
Makes sense, yes at least a mention in the readme would be good. It definitely confused me :)

**Comment by mgckind** [comment]
Will do

**Comment by mgckind** [comment]
I've updated the Readme with clear instructions and also added a FAQ
