### ISSUE TITLE
Oracle client install instructions in the readme are not publicly visible

### ISSUE THREAD

**Issue by ngoldbaum** [mgckind/easyaccess#159]
The readme links to a confluence page for instructions on how to properly set up the oracle client library, which is not publicly visible:

https://opensource.ncsa.illinois.edu/confluence/display/DESDM/Instructions+for+installing+Oracle+client+and+easyaccess+without+EUPS

The contents of this wiki page should be part of the easyaccess docs, since easyaccess seems to crash when I try to login to the database without the client library installed, so it's very important to make it easy and clear how to install that dependency.

It was also not clear to me until I tried to install the client libraries that I'd need to sign up for an oracle account to even get to the download page.

see https://github.com/openjournals/joss-reviews/issues/1022

**Comment by ngoldbaum** [comment]
Just a heads up that I'm blocked on going further on my peer review by this one as I'm not sure how to install the client library to allow me to use easyaccess locally.

**Comment by mgckind** [comment]
Thanks, The main purpose of the library is for the DES collaboration and those are instructions are available for them.
Can you try using conda?
I can also provide you with access to the internal DB to look at some of the functionalities.
Thanks for doing the review!

**Comment by mgckind** [comment]
Were you able installing using conda? I have  a test account setup for you to log in into DES.

**Comment by ngoldbaum** [comment]
You don't think it would be possible to expose the installation instructions in a publicly visible location? I understand that this will be mostly used by the DES collaboration, but I don't think that should prevent people from setting things up on their own system if that's possible, especially if the only thing blocking that is making some documentation that already exists publicly viewable.

I haven't tried to set this up yet using conda, I've been working on other things. My plan was to come back to this today.

**Comment by mgckind** [comment]
I've added clear instructions and remove the links to internal pages, also found out
the  oracle client is indeed free for distribution
https://www.oracle.com/technetwork/database/database-technologies/instant-client/overview/index.html
