### ISSUE TITLE
pip installation

### ISSUE THREAD

**Issue by mgckind** [mgckind/easyaccess#16]
Not working on some systems

**Comment by hoyleb** [comment]
If it helps, I recently tried to reinstall using pip, and while it claimed to work, easyaccess didn't work.

OSX v10.10.4, python handled by Enthough-Canopy

There were a few changes I had to make. 
1) download and unzip fitsio 0.9.7 from pypip
https://pypi.python.org/pypi/fitsio/
In setup.py modify the lines
82.    extra_compile_args=[]#'-arch','i386','-arch','x86_64']
83.    extra_link_args=[]#'-arch','i386','-arch','x86_64']
then 
%>python setup.py install

Next, 
pip install future 
pip install cx_Oracle

Then I had to remove a few lines 7->9 from  easyaccess

#from builtins import input
#from builtins import str
#from builtins import range
and add:
from builtins import *

Now it works!
