### ISSUE TITLE
Unable to access DES data

### ISSUE THREAD

**Issue by ngoldbaum** [mgckind/easyaccess#161]
Not sure if this is the correct place, but I guess I need to take you up on your offer to give me database access manually. I tried filling out the form linked in the readme here: https://des.ncsa.illinois.edu/easyweb/signup/

That did work, but I'm unable to use this login to actually access the database. An account under my e-mail (ngoldbau@illinois.edu) does seem to exist though and I'm able to reset my password, I'm just not able to actually use the account I've made to login.

**Comment by mgckind** [comment]
I'll send you a DES account internally by email, also for the public data you migth need to use `easyaccess -s desdr`

**Comment by ngoldbaum** [comment]
I was able to clear this up, closing
