### ISSUE TITLE
Document license issues when using oracle instant client

### ISSUE THREAD

**Issue by ngoldbaum** [mgckind/easyaccess#162]
Easyaccess depends on the oracle client library. As raised in the JOSS review (https://github.com/openjournals/joss-reviews/issues/1022), this might lead to potential legal issues if someones makes use of easyaccess for production work on a system that hasn't been licensed for production work with Oracle. 

First, we need to verify that this is a real issue. My reading of the OTN license is that yes this is an issue but I'm not a lawyer. @arfon pinged @Kevin-Mattheus-Moerman in the JOSS review issue, perhaps he can weigh in?

If it is a real problem then this concern needs to be explicitly mentioned in the documentation to warn users about potential legal issues when they use easyaccess for production work.

**Comment by ngoldbaum** [comment]
Another issue - are there license issues with distributing the oracle instant client on your conda channel? When I downloaded it from oracle I needed to sign up for an oracle account and explicitly agree to the OTN license before downloading the code.

In particular, in the OTN license it says that redistributors must (among other things):

> (b) keep executed end user agreements and records of end user information including name, address, date of distribution and identity of Programs distributed; (c) allow us to inspect Your end user agreements and records upon request; and, (d) enforce the terms of Your end user agreements so as to effect a timely cure of any end user breach, and to notify us of any breach of the terms. 

Just running a conda channel doesn't do that.

**Comment by arfon** [comment]
Thanks for opening this @ngoldbaum - I've asked NumFOCUS legal to help us resolve this question.

**Comment by mgckind** [comment]
The Oracle instant client which is required by `cx_Oracle` and then by `easyaccess` link is here:https://www.oracle.com/technetwork/database/database-technologies/instant-client/overview/index.html I think there is no issues here since we are nos distributing Oracle by any means, just the client to access the DBs. I've added extra text in the Readme on how to install the client.
https://www.oracle.com/technetwork/database/database-technologies/instant-client/overview/index.html

**Comment by ngoldbaum** [comment]
> I think there is no issues here since we are nos distributing Oracle by any means

Not quite true, since you're running the `mgckind` conda channel which has binaries for the oracle instant client. It is true that you are allowed to do this, but must keep records when people download it as specified in the snippet of the license I linked to in November

Also I'd like to highlight the issue I originally pointed out: the oracle instant client is only licensed for testing and debugging purposes. If someone uses the instant client (or `easyaccess` itself) to do "production" work, they will be breaking the terms of the license and possibly exposing themselves to litigation from oracle.

So there are two issues here, only one of which is a user-facing problem:

* The oracle instant client license does not allow "production" work. Instead, for production work, people must use the full oracle client on e.g. a DES-managed system. This needs some sort of documentation in e.g. the README.

* The conda channel which easyaccess is distributed from may be breaking the oracle instant client license since users who download the client from there are not explicitly agreeing to the oracle license or having their contact information recorded as required by the redistribution clause of the oracle license.

I'm going to put my foot down on documenting this problem before we go further with the JOSS submission. It would also be very nice to get an expert opinion from e.g. someone at NUMFocus. It's possible that my interpretation of the license is incorrect, I'm not a lawyer after all, but I'd really like to get an expert opinion on that before dropping my objections in this issue.

**Comment by ngoldbaum** [comment]
Just in case there's a language issue or a misunderstanding, here are two more points that I think might help elucidate why I'm raising these issues:

• I agree that the oraclie client is “free to download, deploy, and distribute”, but that still means that you have to abide by the license. If Oracle has an issue with the instant client being made available on your conda channel will you be able to comply with their requests for records by giving details of all 196 people who have downloaded the client from your conda channel?
• The user may not be required to have the server installed, but if they use the instant client with `easyaccess` for “production” work (which could occur depending on how users use the data) they could be violating the instant client license. Even if it’s free to download, they may risk legal action.

I’m concerned about both of these issues and am not sure they have been addressed.

I agree that you’ve added clearer instructions in the README about how to download the instant client, but I don’t see adequate documentation of the terms of the instant client license or the requirement that the instant client only be used for testing and debugging purposes and *not* for production work.

**Comment by mgckind** [comment]
Thanks, 
I think you are right, I'll get as much info as possible in order to move forward.

**Comment by mgckind** [comment]
For completeness only, anaconda had the client in their conda channel [here](https://anaconda.org/anaconda/oracle-instantclient), not the os-x version

**Comment by ngoldbaum** [comment]
Ah interesting, I guess a similar issue could be raised with anacona inc (assuming they don’t have a license waiver from Oracle).

**Comment by mgckind** [comment]
I'm contacting Oracle and asking around the building as well.
