### ISSUE TITLE
Add contribution, support instructions

### ISSUE THREAD

**Issue by ngoldbaum** [mgckind/easyaccess#163]
Currently I don't think there are any explicit instructions for how to contribute to `easyaccess` development or how to report issues. Please add a brief mention in the readme and possibly also a more detailed CONTRIBUTING file.

Once this is done I'll check the "community guidelines" checkbox in the JOSS review checklist.

See openjournals/joss-reviews#1022

**Comment by mgckind** [comment]
will do, thanks

**Comment by mgckind** [comment]
I've added a contributions guideline, code of conduct and author files.  They are currently in the [1.4.6 branch](https://github.com/mgckind/easyaccess/tree/1.4.6) soon to be merged. Thanks

**Comment by ngoldbaum** [comment]
Looks like that branch was merged. I looked over the new files and they look good to me. Closing.
