### ISSUE TITLE
crashes when no existing ~/.easyaccess/config.ini

### ISSUE THREAD

**Issue by erykoff** [mgckind/easyaccess#20]
If you don't have an existing config.ini, the default one that is generated is missing essential keywords, causing a crash on startup.  These specific keywords need to be added by hand:

[easyaccess]
nullvalue = -9999
outfile_max_mb = 1000
autocommit = no

[display]
loading_bar = yes

**Comment by mgckind** [comment]
Sometimes there might a be conflict with versions installed using pip and EUPS (when both are present). This is fixed now from the EUPS side to avoid such a conflict. Will change the config.py module name to be less generic as well
