### ISSUE TITLE
views not showing in autocompletion

### ISSUE THREAD

**Issue by mgckind** [mgckind/easyaccess#22]
Need to treat views the same way is done for tables

**Comment by kadrlica** [comment]
Has this been addressed? Do we have a test example?

**Comment by mgckind** [comment]
No, I had few examples somewhere but lost track. I keep this open as a reminder but it is not critical :)
Listing views from all_views have some examples, most of them not very useful though. 
This is a view MOLYGON_SVA1_SNE that is not in the metadata.

**Comment by mgckind** [comment]
Well, that's a bad example as the table/view isn't there. I'll check for more later. But the idea was to have a describe_view if there enough views, otherwise add those views as if they were tables

**Comment by mgckind** [comment]
This is related to #46

**Comment by mgckind** [comment]
Fixed by changing metadata and cache tables in #113 and other places
