### ISSUE TITLE
request for way to redirect query output to a file without embedding within the sql file

### ISSUE THREAD

**Issue by ehneilsen** [mgckind/easyaccess#25]
I would like a mechanism to allow me to run a query from a file that sends its output to a file, where the destination file is not specified within the SQL file, but rather interactively (if easyaccess is being run interactively) or in the bash command (if not).

The current behavior is irritating because I want to be able to easily switch back and forth between easyaccess and other tools, and the current behavior means I have edit the SQL file each time.

**Comment by mgckind** [comment]
Hi, that was the first design. 
I'll think about a better alternative to do so for  the next version, maybe with an extra parameter to the loadsql command.  
A work around would be using easyaccess from inside python. The following script would load the sql statement (without the output file) and then it runs and writes the result in 2 different files.

```
import easyaccess as ea
#connect to DB
con=ea.connect()
#read query from file
query=con.loadsql('my.sql')
#write to file1
con.query_and_save(query, 'output1.csv', print_time=False)
#write to file2
con.query_and_save(query, 'output2.csv', print_time=False)
```

**Comment by mgckind** [comment]
I'm fixing this issue, 

now you can use loadsql or @ to load sql files and override the output filename wirh

DESDB ~> loadsql test.sql > output.csv

or

DESDB ~> @test.sql > myoutput.csv

regardless if the file was already specified inside the sql file

This avoid to rewrite the sql file
