### ISSUE TITLE
looking for a column with wildcards within a specific table

### ISSUE THREAD

**Issue by nsevilla** [mgckind/easyaccess#26]
I'd like to see a command, similar to find_tables_with_column, which would list all columns matching the input for a specific table. Example:

find MAG in table Y1A1_COADD_OBJECTS
...
MAG_MODEL_G
MAG_MODEL_R
MAG_MODEL_I
...

**Comment by mgckind** [comment]
Instead of adding a new command, I've added an option to the describe_table that allows to show only columns with given pattern, if pattern do not match, no columns are displayed,

e.g.
describe_table Y1A1_COADD_OBJECTS with MAG_%

will show all columns starting with MAG_
