### ISSUE TITLE
`import builtins` compatible with python 3 only

### ISSUE THREAD

**Issue by beckermr** [mgckind/easyaccess#31]
I got this error

``` python
ImportError: No module named builtins
```

The `builtins` module is **builtins** in python 2. Can we change this so that it is both python 2 and python 3 compatible.

**Comment by beckermr** [comment]
I think this is `__builtin__` actually.

**Comment by mgckind** [comment]
Thanks, this version is still in development, last stable version is 1.1.0 under releases (for pyhthon 2 only)
builtins come with python-future
http://python-future.org/
is not the internal **future** not **builtins** is a separate module to make transition easier so it can be installed for python2/3

**Comment by beckermr** [comment]
Ahh OK. So if you have `future` installed, you get the packages you need. I am going to close this issue then, since if the user knows about the `future` dependency, then this is not an issue.
