### ISSUE TITLE
undocumented dependencies

### ISSUE THREAD

**Issue by beckermr** [mgckind/easyaccess#32]
It looks like the code needs several dependencies that are not documented. These include 
- future
- configparser

**Comment by mgckind** [comment]
Thanks 
I've added them in the setup.py but yes, I'm still working on this new version.

**Comment by kadrlica** [comment]
Might need to add "builtins" to that list (I just got an ImportError when I tried to update and run on python 2.7.6+3 from DESDM).

**Comment by mgckind** [comment]
Hi,
builtins come with python-future
http://python-future.org/
is not the internal **future** nor **builtins** but a separate module to make transition easier so it can be installed for python2/3

**Comment by kadrlica** [comment]
Ok, thanks. So I guess I'll try to stop hacking things. Do we have python-future in eups?

**Comment by mgckind** [comment]
I added the request to setup.py as Matthew suggested, I haven't created a new version yet, let alone a new eups version.... but I'm closing this issue

**Comment by mgckind** [comment]
We now have python-future in eups (its called future 0.15.0)
