### ISSUE TITLE
Tab complete fails for files with dashes

### ISSUE THREAD

**Issue by kadrlica** [mgckind/easyaccess#34]
Very strange tab completion bug for files with a dash ("-") in them:

```
DESDB ~> !ls -1
test-query1.sql
test-query2.sql
DESDB ~> @t                     # Start of filename
DESDB ~> @test-query            # First tab pushed
DESDB ~> @test-test-query1.sql  # Typed "1" and pushed tab again
```

The part of the filename before the dash is duplicated when the unique filename is completed. The same behavior does not occur if the dashes are replaced by underscores ("_").

**Comment by mgckind** [comment]
Hi,

Its a "bug"/"feature" in the readline module, by default these are the characters that uses for delimitation between words
' \t\n`~!@#$%^&*()-=+[{]}\|;:\'",<>/?'
The same problem will happen with files like test+query.sql, or anyone that include those characters
I will override the function by taking '+' and '-' from the delimiters which I think are the usual characters in a filename.

**Comment by mgckind** [comment]
Thanks for noticing!
