### ISSUE TITLE
query_to_pandas and semicolons

### ISSUE THREAD

**Issue by kadrlica** [mgckind/easyaccess#37]
Should `query_to_pandas`, `query_and_save`, and `query_and_print` (and perhaps others) strip semicolons from queries? Currently they return `invalid character`. It seems like there is some inconsistency here.

**Comment by mgckind** [comment]
absolutely! thanks! I'm on it

**Comment by mgckind** [comment]
query_and_print and query_and_save usually get their queries without semicolons internally, I added a extra line for safety, query_to_pandas was fixed.
