### ISSUE TITLE
Move of old config dir not robust

### ISSUE THREAD

**Issue by kadrlica** [mgckind/easyaccess#39]
This may be a somewhat unique situation, but I work on a machine where I sometimes run the old version of easyaccess and I sometimes run the new version. When I start the new version, it tries to move the misnamed `.easyacess` directory to `.easyacess_old`. If this succeeds, it then breaks the configuration of the old version of `easyaccess`. However, even worse, if the directory `.easyacess_old` already exists, then `shutil` throws an exception. 

I would propose not moving the old `.easyacess` directory if it is found. Instead, I would just copy the old config files into the new config directory if no new config already exists.  In other words, remove [this line](https://github.com/mgckind/easyaccess/blob/823037ead02d633b402e7dee53c537783b877dc5/easyaccess.py#L67).

**Comment by mgckind** [comment]
We need to go back to this issue for a final solution #42

**Comment by mgckind** [comment]
Can we close this?, not sure the changes we have right now solve this.

**Comment by kadrlica** [comment]
I think it's worth doing some beta tests with the new release candidate.

**Comment by mgckind** [comment]
I'll close this, as its been addressed since last version  and doubled checked in the new version
