### ISSUE TITLE
Set config options from the command line

### ISSUE THREAD

**Issue by kadrlica** [mgckind/easyaccess#47]
It would be nice to control the config options for a single session from the command line. An simple option could be:

```
easyaccess -l query.sql -s desoper --config easyaccess outfile_max_mb 2000 --config display color_terminal no
```

where some pseudo code from the argparser would be:

```
parser.add_argument('--config',nargs=3,action='append')
...
for c in args.config:
    conf.set(*c)
```

Of course, the config options formatting can we whatever we want. Another obvious choice is `--config easyaccess.outfile_max_mb.2000` and split on `.`.

**Comment by mgckind** [comment]
What started as a fixing documentation ended up tackling this as well :), 
from the PR
I fixed documentation and added extra features like

--config show : To show current content of config file
--config reset : To reset values to default
--config set param1=value1 param2=value2 etc... : To modify configuration parameters on for the session
