### ISSUE TITLE
query provenance information

### ISSUE THREAD

**Issue by richardgmcmahon** [mgckind/easyaccess#50]
Hi, trivialaccess provide very useful provenance information in the FITS file headers:

e.g.
USERNAME= 'sr525   '           / The user who generated this file  
QUERY   = 'select \* from Y1A1_COADD_OBJECTS where tilename = ''DES2359-5205''' /
ROWLIMIT=                    0 / The maximum number of rows allowed in this file
QRY_DATE= '2015-03-13 20:57:02 UTC' / The date/time the query was executed  
DATA_SRC= 'jdbc:oracle:thin://@leovip148.ncsa.uiuc.edu:1521/dessci' / The connec
COMMENT  select \* from Y1A1_COADD_OBJECTS where tilename = 'DES2359-5205'  
FILE_SET= '0 of 1  '           / This file's part in a file set       

SIMPLE  =                    T  
BITPIX  =                    8  
NAXIS   =                    0  
EXTEND  =                    T / Extensions are permitted  
NEXTEND =                    1 / Number of Extensions  
USERNAME= 'richardgmcmahon'    / The user who generated this file  
QUERY   = 'select ra, dec, tilename, run, coadd_objects_id, object_number, ima&'
CONTINUE'geid_i, catalogid_i, mag_auto_i, magerr_auto_i, mag_auto_y,magerr_a&'  
CONTINUE'uto_y from sva1_coadd_objects where (mag_auto_i < 22.20)' / The SQL tex
ROWLIMIT=                    0 / The maximum number of rows allowed in this file
QRY_DATE= '2015-08-16 10:21:26 UTC' / The date/time the query was executed  
DATA_SRC= 'jdbc:oracle:thin://@leovip148.ncsa.uiuc.edu:1521/dessci' / The connec
COMMENT  select ra, dec, tilename, run, coadd_objects_id, object_number, imageid
FILE_SET= '0 of 1  '           / This file's part in a file set   

Could this feature be provided for easyaccess. It is very useful/essential to have the query when
checking results for reproducibility.

thanks

**Comment by mgckind** [comment]
Thanks for this, I drop the ball while working on the data release. 

This is indeed helpful, I think it can be added easily although it'd be only for fits files, since its the format supporting headers, it can also be added as part of the data structure for HDF5 files. I'll keep this open and trying to get it done for the next release

**Comment by mgckind** [comment]
This will be included in next release, at least for fits files
