### ISSUE TITLE
PATHS for configuration suggestion

### ISSUE THREAD

**Issue by richardgmcmahon** [mgckind/easyaccess#51]
This is mainly for information and might be useful.

After installation I am asked to add these:

setenv PATH $PATH:/home/rgm/soft/des/easyaccess/MACOS/instantclient_11_2
setenv LD_LIBRARY_PATH $LD_LIBRARY_PATH:/home/rgm/soft/des/easyaccess/MACOS/instantclient_11_2
setenv DYLD_LIBRARY_PATH $DYLD_LIBRARY_PATH:/home/rgm/soft/des/easyaccess/MACOS/instantclient_11_2
setenv ORACLE_BASE /home/rgm/soft/des/easyaccess/MACOS/instantclient_11_2
setenv ORACLE_HOME /home/rgm/soft/des/easyaccess/MACOS/instantclient_11_2
setenv ORACLE_LIB_DIR /home/rgm/soft/des/easyaccess/MACOS/instantclient_11_2
setenv ORACLE_INC_DIR /home/rgm/soft/des/easyaccess/MACOS/instantclient_11_2/sdk/include

This gave me some errors since LD_LIBRARY_PATH did not exist in my environment.

Also I acreated an environment variable for the ROOT path which was set during configuration.

This is for tcsh
e.g.
setenv EASYACCESS_ROOT /data/vault/rgm/des/easyaccess/macos

if ($?LD_LIBRARY_PATH) then
    setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${EASYACCESS_ROOT}/instantclient_11_2
else
    setenv LD_LIBRARY_PATH ${EASYACCESS_ROOT}/instantclient_11_2
endif

if ($?DYLD_LIBRARY_PATH) then
    setenv DYLD_LIBRARY_PATH ${DYLD_LIBRARY_PATH}:${EASYACCESS_ROOT}/instantclient_11_2
else
    setenv DYLD_LIBRARY_PATH ${EASYACCESS_ROOT}/instantclient_11_2
endif

etc

**Comment by mgckind** [comment]
Thanks for this comment as well, the painful part is to install cx_oracle. If you don't mind I'll copy these comments to the documentation page in confluence as it can definitely help somebody else as well. 
Thanks!
