### ISSUE TITLE
loadsql command cannot handle queries with > or <

### ISSUE THREAD

**Issue by erykoff** [mgckind/easyaccess#55]
The do_loadsql function treats the > and < as special breaking characters (presumably related to the output code).  But these are valid sql comparison operators prior to the semicolon (;) at the end of the command.  So any query with > or < is invalid via loadsql.

**Comment by hoyleb** [comment]
I had a similar problem, so I changed to this function [within a python script]
d = connection.query_to_pandas(query, prefetch='')

which worked. Recall you don't need to end the query with a ';' in the python script-level interface

**Comment by mgckind** [comment]
Thanks for spotting this. I'm going through some of the old issues right now. I fixed this, now it should work as expected
