### ISSUE TITLE
Anaconda installable?

### ISSUE THREAD

**Issue by kadrlica** [mgckind/easyaccess#57]
Would it be possible/desirable to have easyaccess be installable via anaconda (I don't know much about anaconda yet, but I'm interested)?

**Comment by mgckind** [comment]
It'd be easy to do, but we will always have the trouble of installing Oracle and cx_oracle afterwards. We can definitely consider this option as well

**Comment by kadrlica** [comment]
I thought that anaconda could handle this. There is a cx_oracle distribution here:
https://anaconda.org/anaconda/cx_oracle

**Comment by mgckind** [comment]
Yes, but it relies on having Oracle client installed

**Comment by kadrlica** [comment]
Doesn't anaconda include this as  a dependency? Specifically:
https://anaconda.org/anaconda/oracle-instantclient

I've just tried `conda install cx_oracle` and it grabbed oracle-instantclient: 11.2.0.4.0-0

**Comment by mgckind** [comment]
oh it does!? didn't know that, that would solve several issues. I wasn't sure about freely distributing Oracle without registration, we do under password protected distribution. If that's the case, then I'm defintely in

**Comment by kadrlica** [comment]
It's worth a double check. I didn't uninstall my other oracle libraries before running the anaconda install, so I may have been fooled... but things look promising.

**Comment by kadrlica** [comment]
I've built an `easyaccess` package on anaconda here (https://anaconda.org/kadrlica/easyaccess) and it appears to work (`termcolor` and `fitsio` need to come from user channels).

```
conda install easyaccess -c kadrlica -c omnia
```
