### ISSUE TITLE
Add quick way to count the number of rows in a table

### ISSUE THREAD

**Issue by kadrlica** [mgckind/easyaccess#75]
This may be some derivative of an `explain` statement or caching the number of rows for `describe_table`.

**Comment by kadrlica** [comment]
From Robert

```
select num_rows from all_tables where table_name='SE_OBJECT'
```

**Comment by mgckind** [comment]
I added it to `describe_table`, although those statistics are not always up to date and not available for all table. Usually those are gathered for DES_ADMIN tables. I added an Estimated number of rows in the description of the table when that info is available
