### ISSUE TITLE
Load table fails for files with dashes

### ISSUE THREAD

**Issue by kadrlica** [mgckind/easyaccess#81]
I expect that this is because `-` is an invalid character in table names but I haven't verified this yet. I'm not saying that we necessarily want to do an automatic conversion, but we do need a more obvious error message.

```
> easyaccess -lt allCCDs-ZP-May202016.csv 
Connecting to DB ** dessci ** ...

<class 'cx_Oracle.DatabaseError'>
ORA-00922: missing or invalid option

 Couldn't drop 'ALLCCDS-ZP-MAY202016' (doesn't exist).
```

**Comment by mgckind** [comment]
Noted,

And yes, table names can't have `-`, hence the error. That's the error message from oracle, maybe we can check for hyphens in the filename and raise an Exception, before trying to create the table, we don't want to convert the name. Also, now you have the option --tablename  for custom name.

**Comment by kadrlica** [comment]
Yep, catching it before sounds good.

**Comment by djbrout** [comment]
I appear to have a slightly similar issue although without the hyphen... 
```
easyaccess -lt test.csv
Connecting to DB ** dessci ** ...

<class 'cx_Oracle.DatabaseError'>
ORA-00902: invalid datatype


 Couldn't drop 'TEST' (doesn't exist).
```
