### ISSUE TITLE
oradiag_<username> directory

### ISSUE THREAD

**Issue by kadrlica** [mgckind/easyaccess#82]
I keep finding an `oradiag_<username>` directory appearing in my home directory. This is definitely Oracle's mess, but it would be nice if we could clean it up. A very brief search points to the `ORACLE_BASE` or `ORACLE_HOME` environment variables:
http://stackoverflow.com/questions/3520054/what-is-oradiag-user-folder
http://stackoverflow.com/a/6411111/4075339

Maybe we could set something to get rid of these?

**Comment by mgckind** [comment]
It reappears after deletion, but reading form those links there might be a hacky way around. If that include calling sudo, I wouldn't include it as part of easyaccess. But yeah, it'd be nice to get rid of it. I'll check with Chris as well.

**Comment by kadrlica** [comment]
At zeroth order what I was thinking was setting `ORACLE_HOME` to point to the `.easyaccess` so that the directory was hidden from the user.

**Comment by mgckind** [comment]
But that needs to point to the oracle client folder, so cx_oracle can be properly imported.

**Comment by kadrlica** [comment]
Right, sorry, that was a psuedo idea. What I should have said is "Set whatever env var that controls the placement of `oradiag` to `.easyaccess`"

**Comment by mgckind** [comment]
Right, yeah I got it. I think that should be possible.

**Comment by mgckind** [comment]
I checked this and it hard to get rid of those, unless you change configuration in the oracle client. We have done it here with one particular version for running in production but it was a customized version and only fixable in Linux. I'll close this issue as it can be done just from easyaccess.  Some extra information  here http://stackoverflow.com/questions/3520054/what-is-oradiag-user-folder

**Comment by kadrlica** [comment]
I guess you aren't comfortable building in a utility to delete this directory if it didn't exist when `easyaccess` started but does exist when `easyaccess` exits?

**Comment by mgckind** [comment]
I'd be fine deleting it as some times log information goes there but we aren't using it.  It will be created again at some point so we would need to check every time when launching ea.  Any thoughts?
