### ISSUE TITLE
set_db option

### ISSUE THREAD

**Issue by richardgmcmahon** [mgckind/easyaccess#86]
Is it possible to have a set_db command in easyaccess after you start it in order to change the db. This would complement the show_db command.

It would be nice/convenient to be able to change db after easyaccess has started.

Thanks

**Comment by mgckind** [comment]
Thanks,

I think is possible, although I'm afraid i'll take same time as disconnecting and connecting again as it requires to close the  connection and start one again. However it sounds like a useful feature. I'm also working on making the loading of the cache metadata much faster. (which can be disabled with the -nr option at start)

**Comment by mgckind** [comment]
I've added the option change_db to enable switching between DBs, its very fast as it doesn't refresh the metadata cache. It's on master right now, but it will part of the next release soon. This is a great suggestion, thanks!
