### ISSUE TITLE
Listing Personal Tables

### ISSUE THREAD

**Issue by kadrlica** [mgckind/easyaccess#94]
I've noticed some strange behavior with tab completing and explicitly accessing my personal tables. I find that strange things happen when I prepend my username.

Here are my tables on DESSCI

```
_________
DESDB ~> mytables
    | ☆            |  Press Ctrl-C to abort    Rows : 9, Avg time (rows/sec): 32.3 
List of my tables
               TABLE_NAME  SIZE_GBYTES
1                  SNVETO     0.037109
2                  SNSTAR     0.070312
3         FGOTTENMETADATA     0.002930
4               SNVERSION     0.000061
5              TMP_SNSTAR     1.193359
6       Y2Q1_GW_SNSTAR_V1     1.187500
7  Y2Q1_G184098_SNVETO_V1     0.121094
8  Y2Q1_G184098_SNSTAR_V1     0.070312
9                    TEST     0.000061
```

Here is what happens when I try to tab complete starting with my username.

```
_________
DESDB ~> describe_table KADRLICA.
KADRLICA.MAGLITES_OBJECTS_INDEX_V2  KADRLICA.MAGLITES_OBJECTS_V2        KADRLICA.Y1A1_COADD_ASTROMETRY      KADRLICA.Y2Q2_OBJECTS_V0
```

Some of these tables are my public tables from DESOPER, but I'm not sure where the others (e.g., `Y2Q2_OBJECTS_V0`) reside. They are not listed from DESOPER

```
_________
DESDB ~> mytables
    |☆             |  Press Ctrl-C to abort    Rows : 4, Avg time (rows/sec): 31.6 
List of my tables
             TABLE_NAME  SIZE_GBYTES
1  ALLCCDS_ZP_MAY202016     0.000122
2       FGOTTENMETADATA     0.002930
3          MY_BLACKLIST     0.000488
4    Y2N_UNIQUE_OBJECTS   107.961914
```

Interestingly, from DESOPER, I get a different list of tables when I try to tab complete, but they appear to match my personal tables in DESOPER.

```
_________
DESDB ~> describe_table KADRLICA.
KADRLICA.ALLCCDS_ZP_MAY202016  KADRLICA.MY_BLACKLIST
KADRLICA.FGOTTENMETADATA       KADRLICA.Y2N_UNIQUE_OBJECTS
```

However, trying to tab complete without my username prefix fails

```
_________
DESDB ~> describe_table MY_BLAC
```

**Comment by mgckind** [comment]
I this is no longer a problem, can you please check (not the bin folder should reflect the changes as well)

**Comment by kadrlica** [comment]
I'm still seeing a strange list of tables when I try to tab complete `KADRLICA.` on `DESSCI`.

**Comment by mgckind** [comment]
Oh I see, Maybe there is something I messed up creating the CACHE_\* tables. I'll take a look, it might be a synonymous issue as well. To give some context, CACHE_\* has the tables only visible by me, i.e., your public tables since I'm the one populating that CACHE table, in the tab will appears those tables plus the your own table list (without prefix). Maybe there is something wrong with those tables, but nevertheless the tables from one DB shouldn't be mixed up with the other DB.

Thanks! I'll take a look

**Comment by kadrlica** [comment]
Ok, sort of makes sense. 

My guess with the tables that I can't find anywhere is that they are in the recycling bin or have otherwise been dropped but not purged. However, I looked in the recycling bin and didn't find them.

**Comment by mgckind** [comment]
I fixed the CACHE_* columns and this will not longer be an issue
